import type {NextPage} from 'next'
import Head from 'next/head'
import BodySingle from "dh-marvel/components/layouts/body/single/body-single";
import LayoutGeneral from 'dh-marvel/components/layouts/layout-general';

const Index: NextPage = () => {
    return (
        <LayoutGeneral>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <BodySingle title={"Sample"}>
                holi cards
            </BodySingle>
        </LayoutGeneral>
    )
}

export default Index
